import qualified Test.DocTest

main :: IO ()
main = Test.DocTest.doctest
    [ "-idist/build/autogen"
    , "--fast"
    , "-XApplicativeDo"
    , "-XBangPatterns"
    , "-XBlockArguments"
    , "-XDataKinds"
    , "-XDefaultSignatures"
    , "-XDeriveAnyClass"
    , "-XDeriveFoldable"
    , "-XDeriveFunctor"
    , "-XDeriveGeneric"
    , "-XDeriveLift"
    , "-XDeriveTraversable"
    , "-XDerivingStrategies"
    , "-XDuplicateRecordFields"
    , "-XFlexibleContexts"
    , "-XFlexibleInstances"
    , "-XGeneralizedNewtypeDeriving"
    , "-XMultiParamTypeClasses"
    , "-XMultiWayIf"
    , "-XNamedFieldPuns"
    , "-XOverloadedStrings"
    , "-XScopedTypeVariables"
    , "-XStandaloneDeriving"
    , "-XTypeApplications"
    , "-XTypeOperators"
    , "-XUndecidableInstances"
    , "-XViewPatterns"
    , "src"
    , "ghc"
    ]
